[package]
name = "advent_of_code_2021"
version = "0.1.0"
authors = ["Pierre Viseu Chevalier <pierrechevalier83@gmail.com>"]
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
bit-set = "0.5.2"
drawille = "0.3.0"
pathfinding = "3.0.5"
sorted-vec = "0.7.0"

[features]
